//! What Grenier's read API exchanges, as Rust types generated from the server's OpenAPI
//! document (`packages/api/openapi.json`). `types.rs` is generated by `api-gen`: never edit it.

#[allow(clippy::all, clippy::pedantic)]
mod types;

pub use types::*;
