// Generated by `cargo run -p api-gen` from packages/api/openapi.json: do not edit.

#[doc = "`About`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct About {
    #[doc = "The commit it was built from, or `unknown`."]
    pub commit: ::std::string::String,
    #[doc = "`production` holds the owner's real data; `development` (shared) and `local` (on one machine) hold test data only."]
    pub instance: AboutInstance,
    #[doc = "A name to show for the instance, when the owner gave one."]
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub label: ::std::option::Option<::std::string::String>,
    #[doc = "The version of the server, or `unknown`."]
    pub version: ::std::string::String,
}
#[doc = "`production` holds the owner's real data; `development` (shared) and `local` (on one machine) hold test data only."]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum AboutInstance {
    #[serde(rename = "production")]
    Production,
    #[serde(rename = "development")]
    Development,
    #[serde(rename = "local")]
    Local,
}
impl ::std::fmt::Display for AboutInstance {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Production => f.write_str("production"),
            Self::Development => f.write_str("development"),
            Self::Local => f.write_str("local"),
        }
    }
}
impl ::std::str::FromStr for AboutInstance {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "production" => Ok(Self::Production),
            "development" => Ok(Self::Development),
            "local" => Ok(Self::Local),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for AboutInstance {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AboutInstance {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`Child`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct Child {
    #[serde(default, skip_serializing_if = "::serde_json::Map::is_empty")]
    pub fields: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
    pub id: ::std::string::String,
    pub in_parent: bool,
    pub slug: ::std::string::String,
    pub summary: ::std::string::String,
    pub title: ::std::string::String,
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: HashMap::is_empty"
    )]
    pub titles: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    #[serde(rename = "type")]
    pub type_: ::std::string::String,
}
#[doc = "`Entry`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct Entry {
    pub aliases: ::std::vec::Vec<::std::string::String>,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub archived_at: ::std::option::Option<::std::string::String>,
    pub body: ::std::string::String,
    pub created: ::std::string::String,
    pub fields: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
    pub id: ::std::string::String,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub parent_id: ::std::option::Option<::std::string::String>,
    pub provenance: ::std::collections::HashMap<::std::string::String, EntryProvenanceValue>,
    pub slug: ::std::string::String,
    pub sources: ::std::vec::Vec<Source>,
    pub summary: ::std::string::String,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub superseded_by: ::std::option::Option<::std::string::String>,
    pub tags: ::std::vec::Vec<::std::string::String>,
    pub title: ::std::string::String,
    #[serde(rename = "type")]
    pub type_: ::std::string::String,
    pub updated: ::std::string::String,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub valid_from: ::std::option::Option<::std::string::String>,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub valid_until: ::std::option::Option<::std::string::String>,
    pub verified: bool,
}
#[doc = "`EntryList`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct EntryList {
    pub entries: ::std::vec::Vec<TreeEntry>,
}
#[doc = "`EntryProvenanceValue`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum EntryProvenanceValue {
    #[serde(rename = "extracted")]
    Extracted,
    #[serde(rename = "inferred")]
    Inferred,
    #[serde(rename = "ambiguous")]
    Ambiguous,
}
impl ::std::fmt::Display for EntryProvenanceValue {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Extracted => f.write_str("extracted"),
            Self::Inferred => f.write_str("inferred"),
            Self::Ambiguous => f.write_str("ambiguous"),
        }
    }
}
impl ::std::str::FromStr for EntryProvenanceValue {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "extracted" => Ok(Self::Extracted),
            "inferred" => Ok(Self::Inferred),
            "ambiguous" => Ok(Self::Ambiguous),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for EntryProvenanceValue {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for EntryProvenanceValue {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`EntryRead`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct EntryRead {
    pub ancestors: ::std::vec::Vec<EntryReadAncestorsItem>,
    pub backlinks: ::std::vec::Vec<Link>,
    pub children: ::std::vec::Vec<Child>,
    pub cited_by: ::std::vec::Vec<EntryReadCitedByItem>,
    pub entry: Entry,
    pub hidden_children: i64,
    pub links: ::std::vec::Vec<Link>,
    pub media: ::std::vec::Vec<Medium>,
    pub path: ::std::vec::Vec<::std::string::String>,
    pub references: ::std::vec::Vec<EntryReadReferencesItem>,
    pub titles: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
}
#[doc = "`EntryReadAncestorsItem`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct EntryReadAncestorsItem {
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub id: ::std::option::Option<::std::string::String>,
    pub title: ::std::string::String,
}
#[doc = "`EntryReadCitedByItem`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct EntryReadCitedByItem {
    pub id: ::std::string::String,
    pub slug: ::std::string::String,
    pub title: ::std::string::String,
}
#[doc = "`EntryReadReferencesItem`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct EntryReadReferencesItem {
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub id: ::std::option::Option<::std::string::String>,
    pub reference: ::std::string::String,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub title: ::std::option::Option<::std::string::String>,
}
#[doc = "`FieldDefinition`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct FieldDefinition {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub due: ::std::option::Option<FieldDefinitionDue>,
    pub kind: FieldDefinitionKind,
    #[doc = "The field holds a list of values of its kind, in the order given and without duplicates, such as several sellers or languages; `required` then means at least one. Not with `due` or `recurs`."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub many: ::std::option::Option<bool>,
    pub name: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub recurs: ::std::option::Option<FieldDefinitionRecurs>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub required: ::std::option::Option<bool>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub sensitive: ::std::option::Option<bool>,
    #[doc = "On an `entry` field only: the names of the types its entries may be of, such as `[\"organization\"]`; a write naming an entry of another type is refused. Without it, any entry is accepted."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub types: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub values: ::std::option::Option<::std::vec::Vec<FieldDefinitionValuesItem>>,
}
#[doc = "`FieldDefinitionDue`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct FieldDefinitionDue {
    pub notice: ::std::string::String,
}
#[doc = "`FieldDefinitionKind`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum FieldDefinitionKind {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "integer")]
    Integer,
    #[serde(rename = "number")]
    Number,
    #[serde(rename = "boolean")]
    Boolean,
    #[serde(rename = "date")]
    Date,
    #[serde(rename = "datetime")]
    Datetime,
    #[serde(rename = "duration")]
    Duration,
    #[serde(rename = "enum")]
    Enum,
    #[serde(rename = "money")]
    Money,
    #[serde(rename = "url")]
    Url,
    #[serde(rename = "entry")]
    Entry,
}
impl ::std::fmt::Display for FieldDefinitionKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Text => f.write_str("text"),
            Self::Integer => f.write_str("integer"),
            Self::Number => f.write_str("number"),
            Self::Boolean => f.write_str("boolean"),
            Self::Date => f.write_str("date"),
            Self::Datetime => f.write_str("datetime"),
            Self::Duration => f.write_str("duration"),
            Self::Enum => f.write_str("enum"),
            Self::Money => f.write_str("money"),
            Self::Url => f.write_str("url"),
            Self::Entry => f.write_str("entry"),
        }
    }
}
impl ::std::str::FromStr for FieldDefinitionKind {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "text" => Ok(Self::Text),
            "integer" => Ok(Self::Integer),
            "number" => Ok(Self::Number),
            "boolean" => Ok(Self::Boolean),
            "date" => Ok(Self::Date),
            "datetime" => Ok(Self::Datetime),
            "duration" => Ok(Self::Duration),
            "enum" => Ok(Self::Enum),
            "money" => Ok(Self::Money),
            "url" => Ok(Self::Url),
            "entry" => Ok(Self::Entry),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for FieldDefinitionKind {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for FieldDefinitionKind {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`FieldDefinitionRecurs`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct FieldDefinitionRecurs {
    pub every: FieldDefinitionRecursEvery,
    pub notice: ::std::string::String,
}
#[doc = "`FieldDefinitionRecursEvery`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum FieldDefinitionRecursEvery {
    #[serde(rename = "yearly")]
    Yearly,
    #[serde(rename = "monthly")]
    Monthly,
    #[serde(rename = "weekly")]
    Weekly,
}
impl ::std::fmt::Display for FieldDefinitionRecursEvery {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Yearly => f.write_str("yearly"),
            Self::Monthly => f.write_str("monthly"),
            Self::Weekly => f.write_str("weekly"),
        }
    }
}
impl ::std::str::FromStr for FieldDefinitionRecursEvery {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "yearly" => Ok(Self::Yearly),
            "monthly" => Ok(Self::Monthly),
            "weekly" => Ok(Self::Weekly),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for FieldDefinitionRecursEvery {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for FieldDefinitionRecursEvery {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`FieldDefinitionValuesItem`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct FieldDefinitionValuesItem(::std::string::String);
impl ::std::ops::Deref for FieldDefinitionValuesItem {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<FieldDefinitionValuesItem> for ::std::string::String {
    fn from(value: FieldDefinitionValuesItem) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for FieldDefinitionValuesItem {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for FieldDefinitionValuesItem {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for FieldDefinitionValuesItem {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for FieldDefinitionValuesItem {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`ForbiddenEncoded`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct ForbiddenEncoded {
    pub message: ::std::string::String,
    #[serde(rename = "_tag")]
    pub tag: ForbiddenEncodedTag,
}
#[doc = "`ForbiddenEncodedTag`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum ForbiddenEncodedTag {
    Forbidden,
}
impl ::std::fmt::Display for ForbiddenEncodedTag {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Forbidden => f.write_str("Forbidden"),
        }
    }
}
impl ::std::str::FromStr for ForbiddenEncodedTag {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "Forbidden" => Ok(Self::Forbidden),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for ForbiddenEncodedTag {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ForbiddenEncodedTag {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`InvalidEncoded`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct InvalidEncoded {
    pub message: ::std::string::String,
    #[serde(rename = "_tag")]
    pub tag: InvalidEncodedTag,
}
#[doc = "`InvalidEncodedTag`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum InvalidEncodedTag {
    Invalid,
}
impl ::std::fmt::Display for InvalidEncodedTag {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Invalid => f.write_str("Invalid"),
        }
    }
}
impl ::std::str::FromStr for InvalidEncodedTag {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "Invalid" => Ok(Self::Invalid),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for InvalidEncodedTag {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for InvalidEncodedTag {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`Link`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct Link {
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub field: ::std::option::Option<::std::string::String>,
    pub id: ::std::string::String,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub note: ::std::option::Option<::std::string::String>,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub period: ::std::option::Option<::std::string::String>,
    pub relation: ::std::string::String,
    pub slug: ::std::string::String,
    pub title: ::std::string::String,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub valid_from: ::std::option::Option<::std::string::String>,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub valid_until: ::std::option::Option<::std::string::String>,
}
#[doc = "`Medium`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct Medium {
    pub alt: ::std::string::String,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub duration: ::std::option::Option<f64>,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub height: ::std::option::Option<i64>,
    pub id: ::std::string::String,
    pub kind: ::std::string::String,
    pub mime: ::std::string::String,
    pub position: i64,
    pub sha256: ::std::string::String,
    pub size: i64,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub source_url: ::std::option::Option<::std::string::String>,
    pub url: ::std::string::String,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub width: ::std::option::Option<i64>,
}
#[doc = "`NotFoundEncoded`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct NotFoundEncoded {
    pub message: ::std::string::String,
    #[serde(rename = "_tag")]
    pub tag: NotFoundEncodedTag,
}
#[doc = "`NotFoundEncodedTag`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum NotFoundEncodedTag {
    NotFound,
}
impl ::std::fmt::Display for NotFoundEncodedTag {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::NotFound => f.write_str("NotFound"),
        }
    }
}
impl ::std::str::FromStr for NotFoundEncodedTag {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "NotFound" => Ok(Self::NotFound),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for NotFoundEncodedTag {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for NotFoundEncodedTag {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`PendingReference`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct PendingReference {
    pub cited_by: ::std::vec::Vec<PendingReferenceCitedByItem>,
    pub slug: ::std::string::String,
}
#[doc = "`PendingReferenceCitedByItem`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct PendingReferenceCitedByItem {
    pub id: ::std::string::String,
    pub slug: ::std::string::String,
    pub title: ::std::string::String,
}
#[doc = "`PendingReferences`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct PendingReferences {
    pub pending: ::std::vec::Vec<PendingReference>,
}
#[doc = "`SearchResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct SearchResult {
    pub excerpt: ::std::string::String,
    pub id: ::std::string::String,
    pub path: ::std::vec::Vec<::std::string::String>,
    pub rank: f64,
    pub slug: ::std::string::String,
    pub summary: ::std::string::String,
    pub title: ::std::string::String,
    #[serde(rename = "type")]
    pub type_: ::std::string::String,
}
#[doc = "`SearchResults`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct SearchResults {
    pub results: ::std::vec::Vec<SearchResult>,
}
#[doc = "`Source`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(untagged)]
pub enum Source {
    Entry(SourceEntry),
    Url(SourceUrl),
    Identifier(SourceIdentifier),
    Item(SourceItem),
}
impl ::std::convert::From<SourceEntry> for Source {
    fn from(value: SourceEntry) -> Self {
        Self::Entry(value)
    }
}
impl ::std::convert::From<SourceUrl> for Source {
    fn from(value: SourceUrl) -> Self {
        Self::Url(value)
    }
}
impl ::std::convert::From<SourceIdentifier> for Source {
    fn from(value: SourceIdentifier) -> Self {
        Self::Identifier(value)
    }
}
impl ::std::convert::From<SourceItem> for Source {
    fn from(value: SourceItem) -> Self {
        Self::Item(value)
    }
}
#[doc = "`SourceEntry`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct SourceEntry {
    pub entry: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub note: ::std::option::Option<::std::string::String>,
    pub slug: ::std::string::String,
    pub title: ::std::string::String,
}
#[doc = "`SourceIdentifier`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct SourceIdentifier {
    pub identifier: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub label: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub note: ::std::option::Option<::std::string::String>,
}
#[doc = "`SourceItem`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct SourceItem {
    pub item: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub note: ::std::option::Option<::std::string::String>,
    pub source: ::std::string::String,
}
#[doc = "`SourceUrl`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct SourceUrl {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub note: ::std::option::Option<::std::string::String>,
    pub url: ::std::string::String,
}
#[doc = "`TreeEntry`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct TreeEntry {
    pub id: ::std::string::String,
    pub in_parent: bool,
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub parent_id: ::std::option::Option<::std::string::String>,
    pub slug: ::std::string::String,
    pub title: ::std::string::String,
    #[serde(rename = "type")]
    pub type_: ::std::string::String,
}
#[doc = "`TypeDefinition`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct TypeDefinition {
    pub description: TypeDefinitionDescription,
    pub fields: ::std::vec::Vec<FieldDefinition>,
    pub label: TypeDefinitionLabel,
    pub name: ::std::string::String,
    #[doc = "Entries of the type filed under an entry of the same type are read in their parent, with their fields, as the parts of a whole (the disks of a computer), rather than as entries of their own in the tree."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub read_in_parent: ::std::option::Option<bool>,
    #[doc = "Every entry of the type is sensitive: shown only to a key with the right `sensitive`."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub sensitive: ::std::option::Option<bool>,
}
#[doc = "`TypeDefinitionDescription`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct TypeDefinitionDescription(::std::string::String);
impl ::std::ops::Deref for TypeDefinitionDescription {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<TypeDefinitionDescription> for ::std::string::String {
    fn from(value: TypeDefinitionDescription) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for TypeDefinitionDescription {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for TypeDefinitionDescription {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for TypeDefinitionDescription {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for TypeDefinitionDescription {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`TypeDefinitionLabel`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct TypeDefinitionLabel(::std::string::String);
impl ::std::ops::Deref for TypeDefinitionLabel {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<TypeDefinitionLabel> for ::std::string::String {
    fn from(value: TypeDefinitionLabel) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for TypeDefinitionLabel {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for TypeDefinitionLabel {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for TypeDefinitionLabel {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for TypeDefinitionLabel {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`TypeList`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct TypeList {
    pub types: ::std::vec::Vec<TypeDefinition>,
}
#[doc = "`UnauthorizedEncoded`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct UnauthorizedEncoded {
    pub message: ::std::string::String,
    #[serde(rename = "_tag")]
    pub tag: UnauthorizedEncodedTag,
}
#[doc = "`UnauthorizedEncodedTag`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum UnauthorizedEncodedTag {
    Unauthorized,
}
impl ::std::fmt::Display for UnauthorizedEncodedTag {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Unauthorized => f.write_str("Unauthorized"),
        }
    }
}
impl ::std::str::FromStr for UnauthorizedEncodedTag {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "Unauthorized" => Ok(Self::Unauthorized),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for UnauthorizedEncodedTag {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for UnauthorizedEncodedTag {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = " Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
