-- The place an entry is part of is a dated link `part_of`, with its provenance. The key `parent`
-- of a write says that provenance, as `body` and `summary` say theirs: a field named `parent`
-- would share its key, and is refused, rather than guessed at. The owner renames it first.
DO $$
DECLARE
  clashes text;
BEGIN
  SELECT string_agg(format('the type `%s` has a field `parent`', t.name), ' and ' ORDER BY t.name)
    INTO clashes
    FROM "types" t, jsonb_array_elements(t.fields) AS f
    WHERE t.deleted_at IS NULL AND f ->> 'name' = 'parent';
  IF clashes IS NOT NULL THEN
    RAISE EXCEPTION '%', upper(left(clashes, 1)) || substr(clashes, 2)
      || ': it is the key of the provenance of the place an entry is part of. Rename the field first (`change_type` with `field` and `rename`), then start again.';
  END IF;
END $$;
--> statement-breakpoint
-- Which of the links of one entry comes first: the order they were made in.
ALTER TABLE "links" ADD COLUMN "seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "links_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
-- Each parent becomes a link `part_of` without dates, `unstated` as every link made before the
-- writers were asked, and the oldest of the places of its entry (a `seq` below every other), so
-- that its path is the one it had. A link `part_of` made by hand before, to the same parent, that
-- holds today is the place already, and is only put first; one that is over, or has not begun, is
-- kept as it was and the parent is a stay of its own (its period is the day of the migration). The
-- events keep their past changes of `parent_id`.
WITH migrated AS (
  SELECT "id" AS "source_id", "parent_id" AS "target_id",
    row_number() OVER (ORDER BY "id") - (SELECT count(*) + 1 FROM "entries" WHERE "parent_id" IS NOT NULL) AS "rank",
    EXISTS (
      SELECT 1 FROM "links" l
      WHERE l."source_id" = "entries"."id" AND l."target_id" = "entries"."parent_id"
        AND l."relation" = 'part_of' AND l."field" = ''
        AND (l."valid_from" IS NULL OR l."valid_from" <= current_date)
        AND (l."valid_until" IS NULL OR l."valid_until" >= current_date)
    ) AS "held",
    EXISTS (
      SELECT 1 FROM "links" l
      WHERE l."source_id" = "entries"."id" AND l."target_id" = "entries"."parent_id"
        AND l."relation" = 'part_of' AND l."period" = '' AND l."field" = ''
    ) AS "taken"
  FROM "entries" WHERE "parent_id" IS NOT NULL
), put_first AS (
  UPDATE "links" SET "seq" = m."rank"
  FROM migrated m
  WHERE m."held" AND "links"."source_id" = m."source_id" AND "links"."target_id" = m."target_id"
    AND "links"."relation" = 'part_of' AND "links"."field" = ''
    AND ("links"."valid_from" IS NULL OR "links"."valid_from" <= current_date)
    AND ("links"."valid_until" IS NULL OR "links"."valid_until" >= current_date)
)
INSERT INTO "links" ("source_id", "target_id", "relation", "period", "provenance", "seq")
  SELECT m."source_id", m."target_id", 'part_of',
    CASE WHEN m."taken" THEN to_char(current_date, 'YYYY-MM-DD') ELSE '' END, 'unstated', m."rank"
  FROM migrated m WHERE NOT m."held";--> statement-breakpoint
-- The places an entry is part of form a tree, never a loop: a link `part_of` made by hand before
-- may close one with the parents, and is refused, rather than guessed at. One walk from every
-- entry along the places that hold today finds every entry a walk meets twice.
DO $$
DECLARE
  slugs text[];
  named text;
BEGIN
  WITH RECURSIVE held AS (
    SELECT "source_id", "target_id" FROM "links"
      WHERE "relation" = 'part_of'
        AND ("valid_from" IS NULL OR "valid_from" <= current_date)
        AND ("valid_until" IS NULL OR "valid_until" >= current_date)
  ), walk (id) AS (
    SELECT "source_id" FROM held
    UNION ALL
    SELECT held."target_id" FROM walk JOIN held ON held."source_id" = walk.id
  ) CYCLE id SET looped USING trail
  SELECT array_agg(DISTINCT e.slug ORDER BY e.slug) INTO slugs
    FROM "entries" e WHERE e.id IN (SELECT id FROM walk WHERE looped);
  IF slugs IS NOT NULL THEN
    named := regexp_replace((SELECT string_agg(format('`%s`', s), ', ') FROM unnest(slugs) AS s),
      ', ([^,]*)$', ' and \1');
    RAISE EXCEPTION '%', 'The links `part_of` make a loop: ' || named
      || CASE WHEN cardinality(slugs) = 1 THEN ' is part of itself' ELSE ' are part of one another' END
      || '. Remove one of them (`link` with `remove`), then start again.';
  END IF;
END $$;
--> statement-breakpoint
ALTER TABLE "entries" DROP CONSTRAINT "entries_parent_id_fkey";--> statement-breakpoint
DROP INDEX "entries_parent_id";--> statement-breakpoint
ALTER TABLE "entries" DROP COLUMN "parent_id";--> statement-breakpoint
CREATE INDEX "links_part_of" ON "links" ("target_id","source_id") WHERE relation = 'part_of';
