//! Generates `crates/api/src/types.rs` from the schemas of the server's OpenAPI document, with
//! typify. `cargo run -p api-gen` writes the file; `cargo run -p api-gen -- --check` fails when the
//! file is not what the document gives.

use std::{fs, io::Write, path::PathBuf, process};

/// The OpenAPI document of the server, exported from its schemas (`bun run openapi`).
const DOCUMENT: &str = "../../packages/api/openapi.json";
/// Where the generated types go.
const TYPES: &str = "crates/api/src/types.rs";

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// The Rust types of every schema in `components.schemas`, formatted.
pub fn generate() -> String {
    let text = fs::read_to_string(root().join(DOCUMENT)).expect("the OpenAPI document is readable");
    let document: serde_json::Value = serde_json::from_str(&text).expect("the document is JSON");
    let schemas = document["components"]["schemas"]
        .as_object()
        .expect("the document has schemas")
        .iter()
        .map(|(name, schema)| {
            let mut schema = schema.clone();
            tolerate_unknown_fields(&mut schema);
            let schema: schemars::schema::Schema =
                serde_json::from_value(schema).expect("a schema typify reads");
            (name.clone(), schema)
        });
    let mut space =
        typify::TypeSpace::new(typify::TypeSpaceSettings::default().with_struct_builder(false));
    space
        .add_ref_types(schemas)
        .expect("typify takes the schemas");
    let code = format!(
        "// Generated by `cargo run -p api-gen` from packages/api/openapi.json: do not edit.\n\n{}",
        space.to_stream()
    );
    rustfmt(&code)
}

/// Drops `additionalProperties: false` everywhere in a schema. The server refuses unknown keys in
/// what it is sent, but a client reading its answers must not: an older viewer has to keep
/// working when a newer server adds a key to an answer.
fn tolerate_unknown_fields(schema: &mut serde_json::Value) {
    match schema {
        serde_json::Value::Object(map) => {
            if map.get("additionalProperties") == Some(&serde_json::Value::Bool(false)) {
                map.remove("additionalProperties");
            }
            map.values_mut().for_each(tolerate_unknown_fields);
        }
        serde_json::Value::Array(items) => items.iter_mut().for_each(tolerate_unknown_fields),
        _ => {}
    }
}

/// The code formatted as `cargo fmt` would.
fn rustfmt(code: &str) -> String {
    let mut child = process::Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(process::Stdio::piped())
        .stdout(process::Stdio::piped())
        .spawn()
        .expect("rustfmt runs");
    child
        .stdin
        .take()
        .expect("rustfmt takes stdin")
        .write_all(code.as_bytes())
        .expect("rustfmt reads the code");
    let output = child.wait_with_output().expect("rustfmt ends");
    assert!(
        output.status.success(),
        "rustfmt fails on the generated code"
    );
    String::from_utf8(output.stdout).expect("rustfmt writes UTF-8")
}

fn main() {
    let target = root().join(TYPES);
    let generated = generate();
    if std::env::args().any(|argument| argument == "--check") {
        if fs::read_to_string(&target).ok().as_deref() != Some(generated.as_str()) {
            eprintln!("{TYPES} is out of date: run `bun run generate` in apps/desktop.");
            process::exit(1);
        }
    } else {
        fs::write(&target, generated).expect("the types file is written");
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn the_committed_types_are_those_the_document_gives() {
        let committed = std::fs::read_to_string(super::root().join(super::TYPES))
            .expect("the types file is readable");
        assert!(
            committed == super::generate(),
            "crates/api/src/types.rs is out of date: run `bun run generate` in apps/desktop"
        );
    }
}
